import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <div className={styles.menubar}>
        <img src="https://s3-alpha-sig.figma.com/img/1ebc/d26f/3e624e49c7a2fb19e36aeda93b5bcb3a?Expires=1649030400&Signature=BMHoPftyRxXgPm4VVWK7SFcAK2c7VspJBUpa9dyf37QqVW61c~JdIkTROsb8exxqbSY~gP0w4M7cyt36R4mqJ8kV4vOKBEl7w2RoXKVlRMNRvoFOyJh1M-vE8DE8DhTyDTQzB~nzvte9IOxDN1Nr74yMGwgVWXPbTI3uR8g7jp02zZL9pH4kT8N5FiqW-BvtdYvb4tI4Lsidib02fW-9oQkf2fxpp42KIfz3emwmY1KEzZeDj0MirAKkzEsijg8Gw48tPQi8Krudaii9A4C2TH35UcLhgiRuyDOYDmJrIJ7Dq3li0pkA6cvEsNcnbNuqjSCdtcP10sl2omCPsHU4dw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA"  />
        <p>Hexa Pocket</p>
        <p>Hexa World</p>
        <p>The API</p>
      </div>
      <Head>
        <title>Hexa Pocket</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://s3-alpha-sig.figma.com/img/09cd/fc9e/80f5c54398af1ff7e1ce7483a6d7229f?Expires=1649030400&Signature=FT2~y23aNiEETzb4Rn03YAMIRUS1fNNi18s~98yUH6qgAu1H3vnF73mIkrcVR3F0UUWf-CWP7-dqeGuIZPE0URf35ZFzbLbpYgEuJ-hDIA1i47CeKk07mZUXmm-KEXdEJi24JYIiIYWjayQgyhZH-0PCpudpaeRm0T4qnToalgcVpSXBO7HLXEm7Om6eaLcGki6o6usDwW0XXIDVAkHw6BZQvzhb6hsXxCt3yLHL5ZZDTv~y7YUecg1sjnZ9wzyur73z3C5Qy7ojvnwOJ6kGcUSt1o9shHeT8Be~Afn~MmsNeGchJFqfHh8LkbG3ym0Ay1vf5n0kS61VLli4iQMQGg__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA" 
 sizes="32x32 64x64" type="image/png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Hexa Pocket
        </h1>

        <p className={styles.description}>
          The cryptocurrency wallet. Get <a href="https://www.google.com"> Hexa Pocket</a> now.
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Join Hexa Pocket &rarr;</h2>
            <p>The safest cryptocurrency wallet. Support all network</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Visit Hexa World &rarr;</h2>
            <p>The NFT token marketplace, the NFT creator</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Hexa Pocket API &rarr;</h2>
            <p>Use Hexa Pocket API to create your Dapp.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Hexa World API &rarr;</h2>
            <p>
              Use Hexa World API to create your own cryptocurrency marketplace
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Vercel
            and Replit
        </a>
      </footer>
    </div>
  )
}
